# nixpacks.toml

# Define a lista de pacotes a serem instalados pelo apt-get
[phases.setup]
aptPkgs = [
  "chromium",
  "libglib2.0-0",  
  "libgbm1",
  "libnss3",
  "libxss1",
  "libasound2",
  "libatk-bridge2.0-0",
  "libgtk-3-0"
]

# Define a fase de instalação das dependências do Node.js
[phases.install]
cmds = ["npm install"]

# Define o comando para iniciar a aplicação
[phases.start]
cmd = "npm start"